fullnameOverride: cockroachdb
statefulset:
  replicas: 3
podAffinity:
  preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchLabels:
            app.kubernetes.io/component: cockroachdb
            app.kubernetes.io/instance: cockroachdb
            app.kubernetes.io/name: cockroachdb
        topologyKey: failure-domain.beta.kubernetes.io/zone

tls:
  enabled: no
  certs:
    provided: yes
    tlsSecret: yes
    nodeSecret: cockroachdb-tls
