{{- $public_key := .Values.ssh_public_key }}
{{- range .Values.clusters }}
---
{{- $cluster := set . "sshKey" $public_key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .metadata.name }}-install-config
type: Opaque
data:
  install-config.yaml: {{ $cluster | toPrettyJson | b64enc }}
{{- end }}   